# Generated by Django 5.0.1 on 2025-11-10 14:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roast_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('roast_date', models.DateField(db_index=True)),
                ('roast_time', models.TimeField()),
                ('roast_epoch', models.BigIntegerField()),
                ('operator', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('roaster_type', models.CharField(blank=True, max_length=255)),
                ('roaster_size', models.FloatField(blank=True, null=True)),
                ('roaster_heating', models.IntegerField(blank=True, null=True)),
                ('beans', models.CharField(blank=True, db_index=True, max_length=500)),
                ('weight_in', models.FloatField(blank=True, null=True)),
                ('weight_out', models.FloatField(blank=True, null=True)),
                ('weight_unit', models.CharField(default='g', max_length=10)),
                ('weight_loss', models.FloatField(blank=True, null=True)),
                ('charge_bt', models.FloatField(blank=True, null=True)),
                ('charge_et', models.FloatField(blank=True, null=True)),
                ('tp_time', models.FloatField(blank=True, help_text='Turning point time in seconds', null=True)),
                ('tp_bt', models.FloatField(blank=True, null=True)),
                ('tp_et', models.FloatField(blank=True, null=True)),
                ('dry_time', models.FloatField(blank=True, null=True)),
                ('dry_bt', models.FloatField(blank=True, null=True)),
                ('dry_et', models.FloatField(blank=True, null=True)),
                ('fcs_time', models.FloatField(blank=True, help_text='First crack start time in seconds', null=True)),
                ('fcs_bt', models.FloatField(blank=True, null=True)),
                ('fcs_et', models.FloatField(blank=True, null=True)),
                ('fcs_ror', models.FloatField(blank=True, null=True)),
                ('drop_time', models.FloatField(blank=True, null=True)),
                ('drop_bt', models.FloatField(blank=True, null=True)),
                ('drop_et', models.FloatField(blank=True, null=True)),
                ('total_time', models.FloatField(blank=True, null=True)),
                ('dry_phase_time', models.FloatField(blank=True, null=True)),
                ('mid_phase_time', models.FloatField(blank=True, null=True)),
                ('finish_phase_time', models.FloatField(blank=True, null=True)),
                ('dry_phase_ror', models.FloatField(blank=True, null=True)),
                ('mid_phase_ror', models.FloatField(blank=True, null=True)),
                ('finish_phase_ror', models.FloatField(blank=True, null=True)),
                ('total_ror', models.FloatField(blank=True, null=True)),
                ('dry_phase_delta_temp', models.FloatField(blank=True, null=True)),
                ('mid_phase_delta_temp', models.FloatField(blank=True, null=True)),
                ('finish_phase_delta_temp', models.FloatField(blank=True, null=True)),
                ('whole_color', models.FloatField(blank=True, null=True)),
                ('ground_color', models.FloatField(blank=True, null=True)),
                ('color_system', models.CharField(blank=True, max_length=50)),
                ('heavy_fc', models.BooleanField(default=False)),
                ('low_fc', models.BooleanField(default=False)),
                ('light_cut', models.BooleanField(default=False)),
                ('dark_cut', models.BooleanField(default=False)),
                ('drops', models.BooleanField(default=False)),
                ('oily', models.BooleanField(default=False)),
                ('uneven', models.BooleanField(default=False)),
                ('tipping', models.BooleanField(default=False)),
                ('scorching', models.BooleanField(default=False)),
                ('divots', models.BooleanField(default=False)),
                ('roasting_notes', models.TextField(blank=True)),
                ('cupping_notes', models.TextField(blank=True)),
                ('alog_file', models.FileField(blank=True, null=True, upload_to='alogs/')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='roast_images/')),
                ('timex', models.JSONField(blank=True, default=list)),
                ('temp1', models.JSONField(blank=True, default=list)),
                ('temp2', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-roast_date', '-roast_time'],
                'indexes': [models.Index(fields=['-roast_date', '-roast_time'], name='roasts_roas_roast_d_8c4115_idx'), models.Index(fields=['title'], name='roasts_roas_title_edbfc0_idx'), models.Index(fields=['beans'], name='roasts_roas_beans_e6d0a1_idx')],
            },
        ),
    ]
